/**
 * Vision Delegate Extension
 *
 * 当主模型不支持图片（例如 glm-5.2）时，自动用 glm-5v-turbo 把图片
 * 转成文字描述，再把描述喂给主模型。这样无需手动切换模型就能"看图"。
 *
 * 工作流程：
 *   用户发图片 + 文字
 *     → input 事件拦截
 *     → 检测到当前模型不支持图片
 *     → 调用 glm-5v-turbo 识别每张图片，得到文字描述
 *     → 把描述追加到用户文字后，清空 images
 *     → 主模型（glm-5.2）收到纯文字（含视觉描述），正常回答
 *
 * 放置位置：pi-kit/extensions/vision-delegate.ts（由 pi-kit package 自动加载）
 * 热加载：在 pi 里输入 /reload
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { ImageContent } from "@earendil-works/pi-ai";
import { Type } from "typebox";
import { readFile } from "node:fs/promises";
import { resolve, isAbsolute, extname } from "node:path";

const VISION_MODEL = "glm-5v-turbo";
const VISION_ENDPOINT =
  "https://open.bigmodel.cn/api/coding/paas/v4/chat/completions";

/** 扩展名 → mimeType，与 pi 内置 read 工具支持的图片格式一致。 */
const EXT_TO_MIME: Record<string, string> = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
};

/**
 * 调用 glm-5v-turbo 识别单张图片，返回文字描述。
 * data 为 base64 字符串，mimeType 如 image/png。
 */
async function describeImage(
  apiKey: string,
  data: string,
  mimeType: string,
  userText: string,
  signal?: AbortSignal,
): Promise<string> {
  const prompt = userText.trim()
    ? `你是视觉助手。请先客观、详细地描述这张图片的内容（文字、UI 布局、关键元素、颜色等所有可见信息），然后根据图片内容尝试回答用户的问题。\n\n用户的问题/上下文：${userText.trim()}`
    : `请详细描述这张图片的内容，包括文字、UI 布局、关键元素、颜色等所有可见信息。`;

  const resp = await fetch(VISION_ENDPOINT, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: VISION_MODEL,
      stream: false,
      messages: [
        {
          role: "user",
          content: [
            { type: "text", text: prompt },
            {
              type: "image_url",
              image_url: {
                url: `data:${mimeType};base64,${data}`,
              },
            },
          ],
        },
      ],
    }),
    signal,
  });

  if (!resp.ok) {
    const errText = await resp.text().catch(() => "");
    throw new Error(`glm-5v-turbo HTTP ${resp.status}: ${errText.slice(0, 300)}`);
  }

  const json: any = await resp.json();
  const content = json?.choices?.[0]?.message?.content;
  if (Array.isArray(content)) {
    return content
      .map((c: any) => (typeof c === "string" ? c : c?.text ?? ""))
      .join("");
  }
  return typeof content === "string"
    ? content
    : JSON.stringify(json).slice(0, 500);
}

export default function (pi: ExtensionAPI) {
  pi.on("input", async (event, ctx) => {
    // 跳过扩展自己注入的消息，避免循环
    if (event.source === "extension") return { action: "continue" };

    const images = event.images;
    if (!images || images.length === 0) return { action: "continue" };

    // 当前模型本身支持图片，就不委托，让它自己看
    const model = ctx.model;
    if (model && model.input.includes("image")) return { action: "continue" };

    // 取 API key：委托目标是智谱 glm-5v-turbo，只用智谱凭据
    const candidates = ["zai-coding-cn", "zai"];
    let apiKey: string | undefined;
    for (const p of candidates) {
      apiKey = await ctx.modelRegistry.getApiKeyForProvider(p);
      if (apiKey) break;
    }
    if (!apiKey) {
      ctx.ui.notify(
        "未找到智谱 API key，无法用 glm-5v-turbo 识别图片。请先 /login 智谱。",
        "error",
      );
      return { action: "continue" };
    }

    ctx.ui.setStatus(
      "vision",
      `用 glm-5v-turbo 识别 ${images.length} 张图片…`,
    );
    try {
      const parts: string[] = [];
      for (let i = 0; i < images.length; i++) {
        const desc = await describeImage(
          apiKey,
          images[i].data,
          images[i].mimeType,
          event.text,
          ctx.signal,
        );
        parts.push(
          `[图片 ${i + 1} 的视觉描述（由 ${VISION_MODEL} 提供）]\n${desc.trim()}`,
        );
      }
      const sep = event.text.trim() ? "\n\n" : "";
      const newText = event.text + sep + parts.join("\n\n");
      ctx.ui.notify(
        `已用 ${VISION_MODEL} 识别 ${images.length} 张图片`,
        "info",
      );
      return { action: "transform", text: newText, images: [] };
    } catch (e: any) {
      ctx.ui.notify(`图片识别失败: ${e?.message ?? e}`, "error");
      return { action: "continue" };
    } finally {
      ctx.ui.setStatus("vision", undefined);
    }
  });

  /**
   * describe_image_file 工具：当主模型不支持图片时，让模型主动调用它
   * 来"看"磁盘上的图片文件（代替会返回占位符的 read 工具）。
   *
   * 适用场景：用户说"看一下 ./screenshot.png"、"分析 report.pdf 里的图表"
   * （导出成图片后），或者 agent 想读一个 .png/.jpg 来理解内容。
   */
  pi.registerTool({
    name: "describe_image_file",
    label: "Describe Image File",
    description:
      "Read an image file from disk and return a text description of its content, generated by a vision model. Prefer `read` for image files when the current model supports images (it sends the image directly to the model for richer understanding); use this tool only when the current model cannot view images, to get a text description via a separate vision model. Supports .png, .jpg, .jpeg, .gif, .webp.",
    promptSnippet:
      "Get a text description of an image file on disk (only when the current model can't view images)",
    promptGuidelines: [
      "If the current model supports images, use `read` on image files — it sends the image directly to the model. Use describe_image_file only when the current model cannot view images (e.g. a text-only model), to get a text description via a separate vision model.",
    ],
    parameters: Type.Object({
      path: Type.String({
        description:
          "Path to the image file. Relative paths resolve against the current working directory.",
      }),
      question: Type.Optional(
        Type.String({
          description:
            "Optional question about the image. If provided, the vision model will answer it after describing the image.",
        }),
      ),
    }),
    async execute(_toolCallId, params, signal, _onUpdate, ctx) {
      // 当前模型本身支持图片：让它直接用 read 看，不要委托给 glm-5v-turbo
      const model = ctx.model;
      if (model && model.input.includes("image")) {
        return {
          content: [
            {
              type: "text",
              text: "当前模型支持图像，请改用 read 工具直接查看此图片，能获得更准确的理解。describe_image_file 仅用于当前模型不支持图像时委托识别。",
            },
          ],
          isError: false,
        };
      }

      const rawPath = String(params.path ?? "").trim();
      if (!rawPath) {
        return {
          content: [{ type: "text", text: "Error: path is required." }],
          isError: true,
        };
      }

      const absPath = isAbsolute(rawPath)
        ? rawPath
        : resolve(ctx.cwd, rawPath);
      const ext = extname(absPath).toLowerCase();
      const mimeType = EXT_TO_MIME[ext];
      if (!mimeType) {
        return {
          content: [
            {
              type: "text",
              text: `Error: unsupported image type "${ext}". Supported: png, jpg, jpeg, gif, webp.`,
            },
          ],
          isError: true,
        };
      }

      // 取 API key：委托目标是智谱 glm-5v-turbo，只用智谱凭据
      const candidates = ["zai-coding-cn", "zai"];
      let apiKey: string | undefined;
      for (const p of candidates) {
        apiKey = await ctx.modelRegistry.getApiKeyForProvider(p);
        if (apiKey) break;
      }
      if (!apiKey) {
        return {
          content: [
            {
              type: "text",
              text: "Error: no Zhipu/Z.AI API key found. Run /login for the zai-coding-cn provider first.",
            },
          ],
          isError: true,
        };
      }

      let buffer: Buffer;
      try {
        buffer = await readFile(absPath);
      } catch (e: any) {
        return {
          content: [
            {
              type: "text",
              text: `Error reading file ${rawPath}: ${e?.message ?? e}`,
            },
          ],
          isError: true,
        };
      }

      try {
        const desc = await describeImage(
          apiKey,
          buffer.toString("base64"),
          mimeType,
          String(params.question ?? ""),
          signal,
        );
        return {
          content: [
            {
              type: "text",
              text: `Visual description of ${rawPath} (via ${VISION_MODEL}):\n\n${desc.trim()}`,
            },
          ],
          details: { file: rawPath, mimeType, model: VISION_MODEL },
        };
      } catch (e: any) {
        return {
          content: [
            {
              type: "text",
              text: `Error describing image: ${e?.message ?? e}`,
            },
          ],
          isError: true,
        };
      }
    },
  });
}
